### ISSUE TITLE
Wrong timing on first output of clock divider?

### ISSUE THREAD

**Issue by jeremywen** [aridacity/aridacity-VCVRackPlugins#1]
Output 1 from the clock divider seems to be divided by 16 when it should be the same rate as the clock.

**Comment by cubeleco** [comment]
This is intended; it is active on the first tick of the clock. If there is no reset input it will trigger after the 16th step/division. This was added way before the input override so there was no need to copy the clock.

**Comment by Chaircrusher** [comment]
There is a reason to want a divide by 1 output in a clock divider: So that it is subject to the same 1 sample delay of all the other outputs.  This normally doesn't matter, except for the specific use case that @jeremywen and I are looking for:  doing logic operations on clocks.

![image](https://user-images.githubusercontent.com/482621/65374134-06219480-dc4c-11e9-963c-044143fbdbfd.png)

The way it is now the /1 output of your divider is useless, and to get a properly synced /1 clock you have to delay the clock by 1 sample with a mult.

At any rate having an output on a clock divider labeled '1' producing the same output as the one labeled '16' doesn't make any sense. Not only that, the /1 and /16 outputs aren't in sync:
![image](https://user-images.githubusercontent.com/482621/65374215-0c644080-dc4d-11e9-8392-af76b52045d1.png)
